### ISSUE TITLE
Support python3.6

### ISSUE THREAD

**Issue by DuinoDu** [Jittor/jittor#15]
Guys, awesome job!
Is there any plan for supporting python3.6? Much thanks.

**Comment by Jittor** [comment]
Thanks for reporting. In our testing, python3.7 interpreter is 2X faster than python3.6 interpreter, because the fast call protocol is added in python3.7. So we just move on python3.7 and python3.6 is not supported anymore.

here is the python3.7 install script in ubuntu16.04:
```
sudo add-apt-repository ppa:deadsnakes/ppa -y
sudo apt-get update
sudo apt install python3.7 python3.7-dev -y
# python3.8 need this
# sudo apt install python3.8-distutils
wget -O - https://bootstrap.pypa.io/get-pip.py | sudo -H python3.7
```
reference: https://websiteforstudents.com/installing-the-latest-python-3-7-on-ubuntu-16-04-18-04/

**Comment by DuinoDu** [comment]
Enough for me to move to py3.7.
Thanks！
