### ISSUE TITLE
About sync() function

### ISSUE THREAD

**Issue by Innally** [Jittor/jittor#217]
While I was learning the C-GAN by jittor, I saw a strange function: loss.sync() .
However, I've searched for the jittor document, but it seems that you only have the function prototype declaration:
jittor_core.sync()
Declaration: void sync(const vector<VarHolder*>& vh=vector<VarHolder*>(), bool device_sync=false)

There's no description of what's it for.
And after I removed that line, it seems it still works perfectly, which makes me confuse even more.

Could you please tell me what's the difference between adding sync() and not adding it? I'd be so grateful if you can reply as soon as possible.

**Comment by Jittor** [comment]
sync is used for force synchronize execution， otherwise it will be lazy execution，it is ok to remove 'loss.sync'



---Original---
From: ***@***.***&gt;
Date: Sun, May 23, 2021 21:02 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [Jittor/jittor] About sync() function (#217)




 
While I was learning the C-GAN by jittor, I saw a strange function: loss.sync() .
 However, I've searched for the jittor document, but it seems that you only have the function prototype declaration:
 jittor_core.sync()
 Declaration: void sync(const vector<VarHolder*&gt;&amp; vh=vector<VarHolder*&gt;(), bool device_sync=false)
 
There's no description of what's it for.
 And after I removed that line, it seems it still works perfectly, which makes me confuse even more.
 
Could you please tell me what's the difference between adding sync() and not adding it? I'd be so grateful if you can reply as soon as possible.
