### ISSUE TITLE
Cannot pass the test "python3.7 -m jittor.test.test_example"

### ISSUE THREAD

**Issue by unw9527** [Jittor/jittor#251]
## Describe the bug

When I installed jittor on Linux server, it cannot pass the test `python3.7 -m jittor.test.test_example`. The jittor version on my machine is 1.2.3.73.

## Full Log

```
i 0722 10:44:59.040143 84 compiler.py:869] Jittor(1.2.3.73) src: /home/xxx/anaconda3/envs/subdivnet/lib/python3.7/site-packages/jittor
[i 0722 10:44:59.043440 84 compiler.py:870] g++ at /usr/bin/g++(5.4.0)
[i 0722 10:44:59.043547 84 compiler.py:871] cache_path: /home/xxx/.cache/jittor/default/g++
[i 0722 10:44:59.047004 84 __init__.py:286] Found /usr/local/cuda/bin/nvcc(8.0.61) at /usr/local/cuda/bin/nvcc.
[i 0722 10:44:59.100407 84 __init__.py:286] Found gdb(7.11.1) at /usr/bin/gdb.
[i 0722 10:44:59.103876 84 __init__.py:286] Found addr2line(2.26.1) at /usr/bin/addr2line.
[i 0722 10:44:59.120054 84 compiler.py:958] py_include: -I/home/xxx/anaconda3/envs/subdivnet/include/python3.7m -I/home/xxx/anaconda3/envs/subdivnet/include/python3.7m
[i 0722 10:44:59.136426 84 compiler.py:960] extension_suffix: .cpython-37m-x86_64-linux-gnu.so
[i 0722 10:44:59.282119 84 compiler.py:1098] OS type:ubuntu OS key:ubuntu
[i 0722 10:44:59.283092 84 __init__.py:178] Total mem: 62.83GB, using 16 procs for compiling.
nvcc fatal   : Value 'c++14' is not defined for option 'std'
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/xxx/anaconda3/envs/subdivnet/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/xxx/anaconda3/envs/subdivnet/lib/python3.7/site-packages/jittor_utils/__init__.py", line 152, in do_compile
    return cc.cache_compile(cmd, cache_path, jittor_path)
RuntimeError: [f 0722 10:44:59.318528 84 log.cc:387] Check failed ret(256) == 0(0) Run cmd failed: cd /home/xxx/.cache/jittor/default/g++ && /usr/local/cuda/bin/nvcc /home/xxx/anaconda3/envs/subdivnet/lib/python3.7/site-packages/jittor/src/misc/nan_checker.cu      -std=c++14 -Xcompiler -fPIC  -Xcompiler -march=native  -Xcompiler -fdiagnostics-color=always  -I/home/xxx/anaconda3/envs/subdivnet/lib/python3.7/site-packages/jittor/src -I/home/xxx/anaconda3/envs/subdivnet/include/python3.7m -I/home/xxx/anaconda3/envs/subdivnet/include/python3.7m -DHAS_CUDA -I'/usr/local/cuda/include' -I'/home/xxx/anaconda3/envs/subdivnet/lib/python3.7/site-packages/jittor/extern/cuda/inc'  -I/home/xxx/.cache/jittor/default/g++  -O2  -x cu --cudart=shared -ccbin='/usr/bin/g++'   -w  -I'/home/xxx/anaconda3/envs/subdivnet/lib/python3.7/site-packages/jittor/extern/cuda/inc'  -c  -o /home/xxx/.cache/jittor/default/g++/obj_files/nan_checker.cu.o
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/xxx/anaconda3/envs/subdivnet/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/xxx/anaconda3/envs/subdivnet/lib/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/xxx/anaconda3/envs/subdivnet/lib/python3.7/site-packages/jittor/__init__.py", line 18, in <module>
    from . import compiler
  File "/home/xxx/anaconda3/envs/subdivnet/lib/python3.7/site-packages/jittor/compiler.py", line 1106, in <module>
    compile(cc_path, cc_flags+opt_flags, files, 'jittor_core'+extension_suffix)
  File "/home/xxx/anaconda3/envs/subdivnet/lib/python3.7/site-packages/jittor/compiler.py", line 93, in compile
    jit_utils.run_cmds(cmds, cache_path, jittor_path, "Compiling "+base_output)
  File "/home/xxx/anaconda3/envs/subdivnet/lib/python3.7/site-packages/jittor_utils/__init__.py", line 193, in run_cmds
    for i,_ in enumerate(p.imap_unordered(do_compile, cmds)):
  File "/home/xxx/anaconda3/envs/subdivnet/lib/python3.7/multiprocessing/pool.py", line 748, in next
    raise value
RuntimeError: [f 0722 10:44:59.318528 84 log.cc:387] Check failed ret(256) == 0(0) Run cmd failed: cd /home/xxx/.cache/jittor/default/g++ && /usr/local/cuda/bin/nvcc /home/xxx/anaconda3/envs/subdivnet/lib/python3.7/site-packages/jittor/src/misc/nan_checker.cu      -std=c++14 -Xcompiler -fPIC  -Xcompiler -march=native  -Xcompiler -fdiagnostics-color=always  -I/home/xxx/anaconda3/envs/subdivnet/lib/python3.7/site-packages/jittor/src -I/home/xxx/anaconda3/envs/subdivnet/include/python3.7m -I/home/xxx/anaconda3/envs/subdivnet/include/python3.7m -DHAS_CUDA -I'/usr/local/cuda/include' -I'/home/xxx/anaconda3/envs/subdivnet/lib/python3.7/site-packages/jittor/extern/cuda/inc'  -I/home/xxx/.cache/jittor/default/g++  -O2  -x cu --cudart=shared -ccbin='/usr/bin/g++'   -w  -I'/home/xxx/anaconda3/envs/subdivnet/lib/python3.7/site-packages/jittor/extern/cuda/inc'  -c  -o /home/xxx/.cache/jittor/default/g++/obj_files/nan_checker.cu.o
```

**Comment by Jittor** [comment]
your cuda version is 8.0, we support cuda version &gt;= 10.0, you can upgrade it by command: python3 -m jittor_utils.install_cuda



---Original---
From: ***@***.***&gt;
Date: Thu, Jul 22, 2021 10:48 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [Jittor/jittor] Cannot pass the test "python3.7 -m jittor.test.test_example" (#251)




 
Describe the bug
 
When I installed jittor on Linux server, it cannot pass the test python3.7 -m jittor.test.test_example. The jittor version on my machine is 1.2.3.73.
 
Full Log
 i 0722 10:44:59.040143 84 compiler.py:869] Jittor(1.2.3.73) src: /home/xxx/anaconda3/envs/subdivnet/lib/python3.7/site-packages/jittor [i 0722 10:44:59.043440 84 compiler.py:870] g++ at /usr/bin/g++(5.4.0) [i 0722 10:44:59.043547 84 compiler.py:871] cache_path: /home/xxx/.cache/jittor/default/g++ [i 0722 10:44:59.047004 84 __init__.py:286] Found /usr/local/cuda/bin/nvcc(8.0.61) at /usr/local/cuda/bin/nvcc. [i 0722 10:44:59.100407 84 __init__.py:286] Found gdb(7.11.1) at /usr/bin/gdb. [i 0722 10:44:59.103876 84 __init__.py:286] Found addr2line(2.26.1) at /usr/bin/addr2line. [i 0722 10:44:59.120054 84 compiler.py:958] py_include: -I/home/xxx/anaconda3/envs/subdivnet/include/python3.7m -I/home/xxx/anaconda3/envs/subdivnet/include/python3.7m [i 0722 10:44:59.136426 84 compiler.py:960] extension_suffix: .cpython-37m-x86_64-linux-gnu.so [i 0722 10:44:59.282119 84 compiler.py:1098] OS type:ubuntu OS key:ubuntu [i 0722 10:44:59.283092 84 __init__.py:178] Total mem: 62.83GB, using 16 procs for compiling. nvcc fatal   : Value 'c++14' is not defined for option 'std' multiprocessing.pool.RemoteTraceback:  """ Traceback (most recent call last):   File "/home/xxx/anaconda3/envs/subdivnet/lib/python3.7/multiprocessing/pool.py", line 121, in worker     result = (True, func(*args, **kwds))   File "/home/xxx/anaconda3/envs/subdivnet/lib/python3.7/site-packages/jittor_utils/__init__.py", line 152, in do_compile     return cc.cache_compile(cmd, cache_path, jittor_path) RuntimeError: [f 0722 10:44:59.318528 84 log.cc:387] Check failed ret(256) == 0(0) Run cmd failed: cd /home/xxx/.cache/jittor/default/g++ &amp;&amp; /usr/local/cuda/bin/nvcc /home/xxx/anaconda3/envs/subdivnet/lib/python3.7/site-packages/jittor/src/misc/nan_checker.cu      -std=c++14 -Xcompiler -fPIC  -Xcompiler -march=native  -Xcompiler -fdiagnostics-color=always  -I/home/xxx/anaconda3/envs/subdivnet/lib/python3.7/site-packages/jittor/src -I/home/xxx/anaconda3/envs/subdivnet/include/python3.7m -I/home/xxx/anaconda3/envs/subdivnet/include/python3.7m -DHAS_CUDA -I'/usr/local/cuda/include' -I'/home/xxx/anaconda3/envs/subdivnet/lib/python3.7/site-packages/jittor/extern/cuda/inc'  -I/home/xxx/.cache/jittor/default/g++  -O2  -x cu --cudart=shared -ccbin='/usr/bin/g++'   -w  -I'/home/xxx/anaconda3/envs/subdivnet/lib/python3.7/site-packages/jittor/extern/cuda/inc'  -c  -o /home/xxx/.cache/jittor/default/g++/obj_files/nan_checker.cu.o """ The above exception was the direct cause of the following exception: Traceback (most recent call last):   File "/home/xxx/anaconda3/envs/subdivnet/lib/python3.7/runpy.py", line 183, in _run_module_as_main     mod_name, mod_spec, code = _get_module_details(mod_name, _Error)   File "/home/xxx/anaconda3/envs/subdivnet/lib/python3.7/runpy.py", line 109, in _get_module_details     __import__(pkg_name)   File "/home/xxx/anaconda3/envs/subdivnet/lib/python3.7/site-packages/jittor/__init__.py", line 18, in <module&gt;     from . import compiler   File "/home/xxx/anaconda3/envs/subdivnet/lib/python3.7/site-packages/jittor/compiler.py", line 1106, in <module&gt;     compile(cc_path, cc_flags+opt_flags, files, 'jittor_core'+extension_suffix)   File "/home/xxx/anaconda3/envs/subdivnet/lib/python3.7/site-packages/jittor/compiler.py", line 93, in compile     jit_utils.run_cmds(cmds, cache_path, jittor_path, "Compiling "+base_output)   File "/home/xxx/anaconda3/envs/subdivnet/lib/python3.7/site-packages/jittor_utils/__init__.py", line 193, in run_cmds     for i,_ in enumerate(p.imap_unordered(do_compile, cmds)):   File "/home/xxx/anaconda3/envs/subdivnet/lib/python3.7/multiprocessing/pool.py", line 748, in next     raise value RuntimeError: [f 0722 10:44:59.318528 84 log.cc:387] Check failed ret(256) == 0(0) Run cmd failed: cd /home/xxx/.cache/jittor/default/g++ &amp;&amp; /usr/local/cuda/bin/nvcc /home/xxx/anaconda3/envs/subdivnet/lib/python3.7/site-packages/jittor/src/misc/nan_checker.cu      -std=c++14 -Xcompiler -fPIC  -Xcompiler -march=native  -Xcompiler -fdiagnostics-color=always  -I/home/xxx/anaconda3/envs/subdivnet/lib/python3.7/site-packages/jittor/src -I/home/xxx/anaconda3/envs/subdivnet/include/python3.7m -I/home/xxx/anaconda3/envs/subdivnet/include/python3.7m -DHAS_CUDA -I'/usr/local/cuda/include' -I'/home/xxx/anaconda3/envs/subdivnet/lib/python3.7/site-packages/jittor/extern/cuda/inc'  -I/home/xxx/.cache/jittor/default/g++  -O2  -x cu --cudart=shared -ccbin='/usr/bin/g++'   -w  -I'/home/xxx/anaconda3/envs/subdivnet/lib/python3.7/site-packages/jittor/extern/cuda/inc'  -c  -o /home/xxx/.cache/jittor/default/g++/obj_files/nan_checker.cu.o  
Minimal Reproduce
 
Expected behavior
