### ISSUE TITLE
在windows10下如果设置命令行启动时自动运行chcp 65001会导致import jittor失败

### ISSUE THREAD

**Issue by WuTianyi321** [Jittor/jittor#278]
## Describe the bug
在windows10下，将注册表的【计算机\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Command Processor】下的【autorun】项的值设置为【chcp 65001】会导致在初次import jittor时因cuda缓存目录名包含【:】而失败

## Full Log
```
>>> import jittor as jt
[i 1103 20:30:55.137695 12 compiler.py:941] Jittor(1.3.1.16) src: D:\Programs\Python\Python38\lib\site-packages\jittor
[i 1103 20:30:55.249683 12 compiler.py:942] cl at C:\Users\WuTianyi\.cache\jittor\msvc\VC\_\_\_\_\_\bin\cl.exe(19.29.30133)
[i 1103 20:30:55.249683 12 compiler.py:943] cache_path: C:\Users\WuTianyi\.cache\jittor\jt1.3.1\cl\py3.8.8\Windows-10-10.x6a\AMDRyzen74800Hxc9\default
[i 1103 20:30:55.258679 12 install_cuda.py:51] cuda_driver_version: [11, 2, 0]
[i 1103 20:30:55.361687 12 __init__.py:372] Found C:\Users\WuTianyi\.cache\jittor\jtcuda\cuda11.2_cudnn8_win\bin\nvcc.exe(11.2.67) at C:\Users\WuTianyi\.cache\jittor\jtcuda\cuda11.2_cudnn8_win\bin\nvcc.exe.
[i 1103 20:30:57.318355 12 compiler.py:993] cuda key:cu11.2.67_sm_65001_75_Active_code_page:
[i 1103 20:30:57.320360 12 compiler.py:34] Create cache dir: C:\Users\WuTianyi\.cache\jittor\jt1.3.1\cl\py3.8.8\Windows-10-10.x6a\AMDRyzen74800Hxc9\default\cu11.2.67_sm_65001_75_Active_code_page:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Programs\Python\Python38\lib\site-packages\jittor\__init__.py", line 18, in <module>
    from . import compiler
  File "D:\Programs\Python\Python38\lib\site-packages\jittor\compiler.py", line 1147, in <module>
    make_cache_dir(cache_path)
  File "D:\Programs\Python\Python38\lib\site-packages\jittor\compiler.py", line 35, in make_cache_dir
    os.mkdir(cache_path)
OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: 'C:\\Users\\WuTianyi\\.cache\\jittor\\jt1.3.1\\cl\\py3.8.8\\Windows-10-10.x6a\\AMDRyzen74800Hxc9\\default\\cu11.2.67_sm_65001_75_Active_code_page:'
```

## Minimal Reproduce
在windows10下，将注册表的【计算机\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Command Processor】下的【autorun】项的值设置为【chcp 65001】，在python中import jittor即可复现

## Expected behavior
可以正常import jittor
或者说在compiler.py中make_cache_dir前对cache_path进行合法性检查/剔除cache_path中的不合法字符

**Comment by Jittor** [comment]
谢谢您的反馈，我们会尝试复现一下，您的建议我们在最新版本1.3.1.18采纳了，您可以通过`python -m pip install jittor -U`更新




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Jittor/jittor"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月3日(星期三) 晚上9:04
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[Jittor/jittor] 在windows10下如果设置命令行启动时自动运行chcp 65001会导致import jittor失败 (Issue #278)





 
Describe the bug
 
在windows10下，将注册表的【计算机\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Command Processor】下的【autorun】项的值设置为【chcp 65001】会导致在初次import jittor时因cuda缓存目录名包含【:】而失败
 
Full Log
    
import jittor as jt
 [i 1103 20:30:55.137695 12 compiler.py:941] Jittor(1.3.1.16) src: D:\Programs\Python\Python38\lib\site-packages\jittor
 [i 1103 20:30:55.249683 12 compiler.py:942] cl at C:\Users\WuTianyi.cache\jittor\msvc\VC_____\bin\cl.exe(19.29.30133)
 [i 1103 20:30:55.249683 12 compiler.py:943] cache_path: C:\Users\WuTianyi.cache\jittor\jt1.3.1\cl\py3.8.8\Windows-10-10.x6a\AMDRyzen74800Hxc9\default
 [i 1103 20:30:55.258679 12 install_cuda.py:51] cuda_driver_version: [11, 2, 0]
 [i 1103 20:30:55.361687 12 init.py:372] Found C:\Users\WuTianyi.cache\jittor\jtcuda\cuda11.2_cudnn8_win\bin\nvcc.exe(11.2.67) at C:\Users\WuTianyi.cache\jittor\jtcuda\cuda11.2_cudnn8_win\bin\nvcc.exe.
 [i 1103 20:30:57.318355 12 compiler.py:993] cuda key:cu11.2.67_sm_65001_75_Active_code_page:
 [i 1103 20:30:57.320360 12 compiler.py:34] Create cache dir: C:\Users\WuTianyi.cache\jittor\jt1.3.1\cl\py3.8.8\Windows-10-10.x6a\AMDRyzen74800Hxc9\default\cu11.2.67_sm_65001_75_Active_code_page:
 Traceback (most recent call last):
 File "", line 1, in 
 File "D:\Programs\Python\Python38\lib\site-packages\jittor_init_.py", line 18, in 
 from . import compiler
 File "D:\Programs\Python\Python38\lib\site-packages\jittor\compiler.py", line 1147, in 
 make_cache_dir(cache_path)
 File "D:\Programs\Python\Python38\lib\site-packages\jittor\compiler.py", line 35, in make_cache_dir
 os.mkdir(cache_path)
 OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: 'C:\Users\WuTianyi\.cache\jittor\jt1.3.1\cl\py3.8.8\Windows-10-10.x6a\AMDRyzen74800Hxc9\default\cu11.2.67_sm_65001_75_Active_code_page:'
    
Minimal Reproduce
 
在windows10下，将注册表的【计算机\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Command Processor】下的【autorun】项的值设置为【chcp 65001】，在python中import jittor即可复现
 
Expected behavior
 
可以正常import jittor
 或者说在compiler.py中make_cache_dir前对cache_path进行合法性检查/剔除cache_path中的不合法字符
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by WuTianyi321** [comment]
问题已解决
