### ISSUE TITLE
import jittor时由于windows10下VC没有M_PI定义导致编译出错

### ISSUE THREAD

**Issue by WuTianyi321** [Jittor/jittor#279]
## Describe the bug
在windows10下import jittor时由于VC没有M_PI的宏定义导致编译出错

## Full Log

```
>>>import jittor
[i 1103 21:03:15.504443 72 compiler.py:941] Jittor(1.3.1.16) src: D:\Programs\Python\Python38\lib\site-packages\jittor
[i 1103 21:03:15.587615 72 compiler.py:942] cl at C:\Users\WuTianyi\.cache\jittor\msvc\VC\_\_\_\_\_\bin\cl.exe(19.29.30133)
[i 1103 21:03:15.589635 72 compiler.py:943] cache_path: C:\Users\WuTianyi\.cache\jittor\jt1.3.1\cl\py3.8.8\Windows-10-10.x6a\AMDRyzen74800Hxc9\default
[i 1103 21:03:15.598616 72 install_cuda.py:51] cuda_driver_version: [11, 2, 0]
[i 1103 21:03:15.798193 72 __init__.py:372] Found C:\Users\WuTianyi\.cache\jittor\jtcuda\cuda11.2_cudnn8_win\bin\nvcc.exe(11.2.67) at C:\Users\WuTianyi\.cache\jittor\jtcuda\cuda11.2_cudnn8_win\bin\nvcc.exe.
[i 1103 21:03:17.652318 72 compiler.py:993] cuda key:cu11.2.67_sm_75
[i 1103 21:03:17.654301 72 compiler.py:34] Create cache dir: C:\Users\WuTianyi\.cache\jittor\jt1.3.1\cl\py3.8.8\Windows-10-10.x6a\AMDRyzen74800Hxc9\default\cu11.2.67_sm_75
[i 1103 21:03:17.656314 72 compiler.py:34] Create cache dir: C:\Users\WuTianyi\.cache\jittor\jt1.3.1\cl\py3.8.8\Windows-10-10.x6a\AMDRyzen74800Hxc9\default\cu11.2.67_sm_75\jit
[i 1103 21:03:17.658311 72 compiler.py:34] Create cache dir: C:\Users\WuTianyi\.cache\jittor\jt1.3.1\cl\py3.8.8\Windows-10-10.x6a\AMDRyzen74800Hxc9\default\cu11.2.67_sm_75\obj_files
[i 1103 21:03:17.660310 72 compiler.py:34] Create cache dir: C:\Users\WuTianyi\.cache\jittor\jt1.3.1\cl\py3.8.8\Windows-10-10.x6a\AMDRyzen74800Hxc9\default\cu11.2.67_sm_75\gen
[i 1103 21:03:17.662313 72 compiler.py:34] Create cache dir: C:\Users\WuTianyi\.cache\jittor\jt1.3.1\cl\py3.8.8\Windows-10-10.x6a\AMDRyzen74800Hxc9\default\cu11.2.67_sm_75\tmp
[i 1103 21:03:17.663310 72 compiler.py:34] Create cache dir: C:\Users\WuTianyi\.cache\jittor\jt1.3.1\cl\py3.8.8\Windows-10-10.x6a\AMDRyzen74800Hxc9\default\cu11.2.67_sm_75\checkpoints
[i 1103 21:03:17.674308 72 __init__.py:187] Total mem: 15.37GB, using 5 procs for compiling.
Compiling jit_utils_core(5/5) used: 2.407s eta: 0.000s
[e 1103 21:03:45.296000 76 log.cc:526] cpu_math.cc1.344s
D:\Programs\Python\Python38\lib\site-packages\jittor\src\misc\cpu_math.cc(47): error C2065: 'M_PI': undeclared identifier
D:\Programs\Python\Python38\lib\site-packages\jittor\src\misc\cpu_math.cc(53): note: see reference to function template instantiation 'float jittor::calc_erfinv<float>(T)' being compiled
        with
        [
            T=float
        ]
D:\Programs\Python\Python38\lib\site-packages\jittor\src\misc\cpu_math.cc(48): error C2065: 'M_PI': undeclared identifier

multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "d:\programs\python\python38\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "D:\Programs\Python\Python38\lib\site-packages\jittor_utils\__init__.py", line 157, in do_compile
    return cc.cache_compile(cmd, cache_path, jittor_path)
RuntimeError: [f 1103 21:03:45.298000 76 log.cc:569] Check failed ret(2) == 0(0) Run cmd failed: "C:\Users\WuTianyi\.cache\jittor\msvc\VC\_\_\_\_\_\bin\cl.exe" "D:\Programs\Python\Python38\lib\site-packages\jittor\src\misc\cpu_math.cc"   -std:c++17        -EHa -MD  -nologo -I"C:\Users\WuTianyi\.cache\jittor\msvc\VC\include" -I"C:\Users\WuTianyi\.cache\jittor\msvc\win10_kits\include\ucrt" -I"C:\Users\WuTianyi\.cache\jittor\msvc\win10_kits\include\shared" -I"C:\Users\WuTianyi\.cache\jittor\msvc\win10_kits\include\um" -DNOMINMAX   -I"D:\Programs\Python\Python38\lib\site-packages\jittor\src" -I"d:\programs\python\python38\include" -DHAS_CUDA -I"C:\Users\WuTianyi\.cache\jittor\jtcuda\cuda11.2_cudnn8_win\include" -I"D:\Programs\Python\Python38\lib\site-packages\jittor\extern\cuda\inc"   -I"C:\Users\WuTianyi\.cache\jittor\jt1.3.1\cl\py3.8.8\Windows-10-10.x6a\AMDRyzen74800Hxc9\default\cu11.2.67_sm_75"   -O2   -c -Fo: "C:\Users\WuTianyi\.cache\jittor\jt1.3.1\cl\py3.8.8\Windows-10-10.x6a\AMDRyzen74800Hxc9\default\cu11.2.67_sm_75\obj_files\cpu_math.cc.obj"
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Programs\Python\Python38\lib\site-packages\jittor\__init__.py", line 18, in <module>
    from . import compiler
  File "D:\Programs\Python\Python38\lib\site-packages\jittor\compiler.py", line 1299, in <module>
    compile(cc_path, cc_flags+opt_flags, files, 'jittor_core'+extension_suffix)
  File "D:\Programs\Python\Python38\lib\site-packages\jittor\compiler.py", line 147, in compile
    jit_utils.run_cmds(cmds, cache_path, jittor_path, "Compiling "+base_output)
  File "D:\Programs\Python\Python38\lib\site-packages\jittor_utils\__init__.py", line 211, in run_cmds
    for i,_ in enumerate(p.imap_unordered(do_compile, cmds)):
  File "D:\Programs\Python\Python38\lib\multiprocessing\pool.py", line 868, in next
    raise value
RuntimeError: [f 1103 21:03:45.298000 76 log.cc:569] Check failed ret(2) == 0(0) Run cmd failed: "C:\Users\WuTianyi\.cache\jittor\msvc\VC\_\_\_\_\_\bin\cl.exe" "D:\Programs\Python\Python38\lib\site-packages\jittor\src\misc\cpu_math.cc"   -std:c++17        -EHa -MD  -nologo -I"C:\Users\WuTianyi\.cache\jittor\msvc\VC\include" -I"C:\Users\WuTianyi\.cache\jittor\msvc\win10_kits\include\ucrt" -I"C:\Users\WuTianyi\.cache\jittor\msvc\win10_kits\include\shared" -I"C:\Users\WuTianyi\.cache\jittor\msvc\win10_kits\include\um" -DNOMINMAX   -I"D:\Programs\Python\Python38\lib\site-packages\jittor\src" -I"d:\programs\python\python38\include" -DHAS_CUDA -I"C:\Users\WuTianyi\.cache\jittor\jtcuda\cuda11.2_cudnn8_win\include" -I"D:\Programs\Python\Python38\lib\site-packages\jittor\extern\cuda\inc"   -I"C:\Users\WuTianyi\.cache\jittor\jt1.3.1\cl\py3.8.8\Windows-10-10.x6a\AMDRyzen74800Hxc9\default\cu11.2.67_sm_75"   -O2   -c -Fo: "C:\Users\WuTianyi\.cache\jittor\jt1.3.1\cl\py3.8.8\Windows-10-10.x6a\AMDRyzen74800Hxc9\default\cu11.2.67_sm_75\obj_files\cpu_math.cc.obj"
```

## Minimal Reproduce

在默认使用VC作为编译器的windows10平台上import jittor

## Expected behavior
正常import jittor

在我使用vc的win10这里，在src/misc/cpu_math.cc下加入一行`#define M_PI 3.14159265358979323846`就可以编译通过了。

**Comment by Jittor** [comment]
谢谢您的反馈，我们在最新版本1.3.1.18修复了该问题，您可以通过`python -m pip install jittor -U`更新




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Jittor/jittor"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月3日(星期三) 晚上9:28
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[Jittor/jittor] 初次import jittor时由于windows10下VC没有M_PI定义导致编译出错 (Issue #279)





 
Describe the bug
 
在windows10下import jittor时由于VC没有M_PI的宏定义导致编译出错
 
Full Log
    
import jittor
 [i 1103 21:03:15.504443 72 compiler.py:941] Jittor(1.3.1.16) src: D:\Programs\Python\Python38\lib\site-packages\jittor
 [i 1103 21:03:15.587615 72 compiler.py:942] cl at C:\Users\WuTianyi.cache\jittor\msvc\VC_____\bin\cl.exe(19.29.30133)
 [i 1103 21:03:15.589635 72 compiler.py:943] cache_path: C:\Users\WuTianyi.cache\jittor\jt1.3.1\cl\py3.8.8\Windows-10-10.x6a\AMDRyzen74800Hxc9\default
 [i 1103 21:03:15.598616 72 install_cuda.py:51] cuda_driver_version: [11, 2, 0]
 [i 1103 21:03:15.798193 72 init.py:372] Found C:\Users\WuTianyi.cache\jittor\jtcuda\cuda11.2_cudnn8_win\bin\nvcc.exe(11.2.67) at C:\Users\WuTianyi.cache\jittor\jtcuda\cuda11.2_cudnn8_win\bin\nvcc.exe.
 [i 1103 21:03:17.652318 72 compiler.py:993] cuda key:cu11.2.67_sm_75
 [i 1103 21:03:17.654301 72 compiler.py:34] Create cache dir: C:\Users\WuTianyi.cache\jittor\jt1.3.1\cl\py3.8.8\Windows-10-10.x6a\AMDRyzen74800Hxc9\default\cu11.2.67_sm_75
 [i 1103 21:03:17.656314 72 compiler.py:34] Create cache dir: C:\Users\WuTianyi.cache\jittor\jt1.3.1\cl\py3.8.8\Windows-10-10.x6a\AMDRyzen74800Hxc9\default\cu11.2.67_sm_75\jit
 [i 1103 21:03:17.658311 72 compiler.py:34] Create cache dir: C:\Users\WuTianyi.cache\jittor\jt1.3.1\cl\py3.8.8\Windows-10-10.x6a\AMDRyzen74800Hxc9\default\cu11.2.67_sm_75\obj_files
 [i 1103 21:03:17.660310 72 compiler.py:34] Create cache dir: C:\Users\WuTianyi.cache\jittor\jt1.3.1\cl\py3.8.8\Windows-10-10.x6a\AMDRyzen74800Hxc9\default\cu11.2.67_sm_75\gen
 [i 1103 21:03:17.662313 72 compiler.py:34] Create cache dir: C:\Users\WuTianyi.cache\jittor\jt1.3.1\cl\py3.8.8\Windows-10-10.x6a\AMDRyzen74800Hxc9\default\cu11.2.67_sm_75\tmp
 [i 1103 21:03:17.663310 72 compiler.py:34] Create cache dir: C:\Users\WuTianyi.cache\jittor\jt1.3.1\cl\py3.8.8\Windows-10-10.x6a\AMDRyzen74800Hxc9\default\cu11.2.67_sm_75\checkpoints
 [i 1103 21:03:17.674308 72 init.py:187] Total mem: 15.37GB, using 5 procs for compiling.
 Compiling jit_utils_core(5/5) used: 2.407s eta: 0.000s
 [e 1103 21:03:45.296000 76 log.cc:526] cpu_math.cc1.344s
 D:\Programs\Python\Python38\lib\site-packages\jittor\src\misc\cpu_math.cc(47): error C2065: 'M_PI': undeclared identifier
 D:\Programs\Python\Python38\lib\site-packages\jittor\src\misc\cpu_math.cc(53): note: see reference to function template instantiation 'float jittor::calc_erfinv(T)' being compiled
 with
 [
 T=float
 ]
 D:\Programs\Python\Python38\lib\site-packages\jittor\src\misc\cpu_math.cc(48): error C2065: 'M_PI': undeclared identifier
    
multiprocessing.pool.RemoteTraceback:
 """
 Traceback (most recent call last):
 File "d:\programs\python\python38\lib\multiprocessing\pool.py", line 125, in worker
 result = (True, func(*args, **kwds))
 File "D:\Programs\Python\Python38\lib\site-packages\jittor_utils_init_.py", line 157, in do_compile
 return cc.cache_compile(cmd, cache_path, jittor_path)
 RuntimeError: [f 1103 21:03:45.298000 76 log.cc:569] Check failed ret(2) == 0(0) Run cmd failed: "C:\Users\WuTianyi.cache\jittor\msvc\VC_____\bin\cl.exe" "D:\Programs\Python\Python38\lib\site-packages\jittor\src\misc\cpu_math.cc"   -std:c++17        -EHa -MD  -nologo -I"C:\Users\WuTianyi.cache\jittor\msvc\VC\include" -I"C:\Users\WuTianyi.cache\jittor\msvc\win10_kits\include\ucrt" -I"C:\Users\WuTianyi.cache\jittor\msvc\win10_kits\include\shared" -I"C:\Users\WuTianyi.cache\jittor\msvc\win10_kits\include\um" -DNOMINMAX   -I"D:\Programs\Python\Python38\lib\site-packages\jittor\src" -I"d:\programs\python\python38\include" -DHAS_CUDA -I"C:\Users\WuTianyi.cache\jittor\jtcuda\cuda11.2_cudnn8_win\include" -I"D:\Programs\Python\Python38\lib\site-packages\jittor\extern\cuda\inc"   -I"C:\Users\WuTianyi.cache\jittor\jt1.3.1\cl\py3.8.8\Windows-10-10.x6a\AMDRyzen74800Hxc9\default\cu11.2.67_sm_75"   -O2   -c -Fo: "C:\Users\WuTianyi.cache\jittor\jt1.3.1\cl\py3.8.8\Windows-10-10.x6a\AMDRyzen74800Hxc9\default\cu11.2.67_sm_75\obj_files\cpu_math.cc.obj"
 """
 
The above exception was the direct cause of the following exception:
 
Traceback (most recent call last):
 File "", line 1, in 
 File "D:\Programs\Python\Python38\lib\site-packages\jittor_init_.py", line 18, in 
 from . import compiler
 File "D:\Programs\Python\Python38\lib\site-packages\jittor\compiler.py", line 1299, in 
 compile(cc_path, cc_flags+opt_flags, files, 'jittor_core'+extension_suffix)
 File "D:\Programs\Python\Python38\lib\site-packages\jittor\compiler.py", line 147, in compile
 jit_utils.run_cmds(cmds, cache_path, jittor_path, "Compiling "+base_output)
 File "D:\Programs\Python\Python38\lib\site-packages\jittor_utils_init_.py", line 211, in run_cmds
 for i,_ in enumerate(p.imap_unordered(do_compile, cmds)):
 File "D:\Programs\Python\Python38\lib\multiprocessing\pool.py", line 868, in next
 raise value
 RuntimeError: [f 1103 21:03:45.298000 76 log.cc:569] Check failed ret(2) == 0(0) Run cmd failed: "C:\Users\WuTianyi.cache\jittor\msvc\VC_____\bin\cl.exe" "D:\Programs\Python\Python38\lib\site-packages\jittor\src\misc\cpu_math.cc"   -std:c++17        -EHa -MD  -nologo -I"C:\Users\WuTianyi.cache\jittor\msvc\VC\include" -I"C:\Users\WuTianyi.cache\jittor\msvc\win10_kits\include\ucrt" -I"C:\Users\WuTianyi.cache\jittor\msvc\win10_kits\include\shared" -I"C:\Users\WuTianyi.cache\jittor\msvc\win10_kits\include\um" -DNOMINMAX   -I"D:\Programs\Python\Python38\lib\site-packages\jittor\src" -I"d:\programs\python\python38\include" -DHAS_CUDA -I"C:\Users\WuTianyi.cache\jittor\jtcuda\cuda11.2_cudnn8_win\include" -I"D:\Programs\Python\Python38\lib\site-packages\jittor\extern\cuda\inc"   -I"C:\Users\WuTianyi.cache\jittor\jt1.3.1\cl\py3.8.8\Windows-10-10.x6a\AMDRyzen74800Hxc9\default\cu11.2.67_sm_75"   -O2   -c -Fo: "C:\Users\WuTianyi.cache\jittor\jt1.3.1\cl\py3.8.8\Windows-10-10.x6a\AMDRyzen74800Hxc9\default\cu11.2.67_sm_75\obj_files\cpu_math.cc.obj"
 
Minimal Reproduce
 
在默认使用VC作为编译器的windows10平台上初次import jittor
 
Expected behavior
 
正常import jittor
 
在我使用vc的win10这里，在src/misc/cpu_math.cc下加入一行#define M_PI 3.14159265358979323846就可以编译通过了。
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by WuTianyi321** [comment]
问题已解决
