### ISSUE TITLE
给的docker里面的jittor 版本还是1.2.2.59，能不能提供下最新的版本的啊

### ISSUE THREAD

**Issue by liufeinuaa** [Jittor/jittor#285]
## Describe the bug

给的docker里面的jittor 版本（尝试的jittor-cuda-11-1）还是1.2.2.59，能不能提供下最新的版本的啊

## Full Log
```
root@5fc319f1597d:/media# /usr/bin/python3 /media/docker-jittor-cuda/ts1.py
[i 1217 15:17:09.308695 36 compiler.py:851] Jittor(1.2.2.59) src: /usr/local/lib/python3.8/dist-packages/jittor
[i 1217 15:17:09.308783 36 compiler.py:852] g++ at /usr/bin/g++
[i 1217 15:17:09.308817 36 compiler.py:853] cache_path: /root/.cache/jittor/default/g++
[i 1217 15:17:09.330789 36 __init__.py:257] Found /usr/local/cuda/bin/nvcc(11.1.105) at /usr/local/cuda/bin/nvcc.
[i 1217 15:17:09.352898 36 __init__.py:257] Found addr2line(2.34) at /usr/bin/addr2line.
[i 1217 15:17:09.375301 36 compiler.py:893] pybind_include: -I/usr/include/python3.8 -I/usr/local/lib/python3.8/dist-packages/pybind11/include
[i 1217 15:17:09.386878 36 compiler.py:895] extension_suffix: .cpython-38-x86_64-linux-gnu.so
[i 1217 15:17:09.507388 36 __init__.py:169] Total mem: 31.31GB, using 10 procs for compiling.
[i 1217 15:17:09.611967 36 jit_compiler.cc:21] Load cc_path: /usr/bin/g++
[i 1217 15:17:09.612003 36 init.cc:54] Found cuda archs: []
[i 1217 15:17:09.687928 36 __init__.py:257] Found mpicc(4.0.3) at /usr/bin/mpicc.
[i 1217 15:17:09.707734 36 compiler.py:658] handle pyjt_include/usr/local/lib/python3.8/dist-packages/jittor/extern/mpi/inc/mpi_warper.h
[i 1217 15:17:09.723767 36 compile_extern.py:289] Downloading nccl...
[i 1217 15:17:09.762774 36 compile_extern.py:16] found /usr/local/cuda/include/cublas.h
[i 1217 15:17:09.762906 36 compile_extern.py:16] found /usr/local/cuda/lib64/libcublas.so
[i 1217 15:17:09.775295 36 compile_extern.py:16] found /usr/include/cudnn.h
[i 1217 15:17:09.775351 36 compile_extern.py:16] found /usr/lib/x86_64-linux-gnu/libcudnn.so
[i 1217 15:17:09.780108 36 compile_extern.py:16] found /usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so
[i 1217 15:17:09.782843 36 compile_extern.py:16] found /usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so
[i 1217 15:17:09.783217 36 compile_extern.py:16] found /usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so
[i 1217 15:17:09.978729 36 compile_extern.py:16] found /usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so
[i 1217 15:17:09.986669 36 compiler.py:658] handle pyjt_include/usr/local/lib/python3.8/dist-packages/jittor/extern/cuda/cudnn/inc/cudnn_warper.h
[i 1217 15:17:09.997169 36 compile_extern.py:16] found /usr/local/cuda/include/curand.h
[i 1217 15:17:09.997244 36 compile_extern.py:16] found /usr/local/cuda/lib64/libcurand.so
1.2.2.59
```
尝试在docker中更新至最新版
pip3 install --upgrade jittor
运行一个最简单的脚本会报错
```
root@5fc319f1597d:/media# /usr/bin/python3 /media/docker-jittor-cuda/ts1.py
[i 1217 15:33:27.779483 88 compiler.py:944] Jittor(1.3.1.27) src: /usr/local/lib/python3.8/dist-packages/jittor
[i 1217 15:33:27.782166 88 compiler.py:945] g++ at /usr/bin/g++(9.3.0)
[i 1217 15:33:27.782256 88 compiler.py:946] cache_path: /root/.cache/jittor/jt1.3.1/g++9.3.0/py3.8.5/Linux-5.8.0-63x08/AMDRyzen73700Xx25/default
[i 1217 15:33:27.784723 88 __init__.py:372] Found nvcc(11.1.105) at /usr/local/cuda/bin/nvcc.
[i 1217 15:33:27.786944 88 __init__.py:372] Found addr2line(2.34) at /usr/bin/addr2line.
[i 1217 15:33:27.890798 88 compiler.py:997] cuda key:cu11.1.105
[i 1217 15:33:28.016007 88 __init__.py:187] Total mem: 31.31GB, using 10 procs for compiling.
[i 1217 15:33:28.103960 88 jit_compiler.cc:27] Load cc_path: /usr/bin/g++
[i 1217 15:33:28.104280 88 init.cc:61] Found cuda archs: []
[i 1217 15:33:28.214387 88 __init__.py:372] Found mpicc(4.0.3) at /usr/bin/mpicc.
[i 1217 15:33:28.246409 88 compile_extern.py:313] Downloading cutt...
Downloading https://codeload.github.com/Jittor/cutt/zip/v1.2 to /root/.cache/jittor/cutt/cutt-1.2.zip
0.00B [00:00, ?B/s]<urlopen error [Errno -3] Temporary failure in name resolution>
Download File failed, url: https://codeload.github.com/Jittor/cutt/zip/v1.2, path: /root/.cache/jittor/cutt/cutt-1.2.zip
Traceback (most recent call last):
  File "/usr/lib/python3.8/urllib/request.py", line 1350, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib/python3.8/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 950, in send
    self.connect()
  File "/usr/lib/python3.8/http/client.py", line 1417, in connect
    super().connect()
  File "/usr/lib/python3.8/http/client.py", line 921, in connect
    self.sock = self._create_connection(
  File "/usr/lib/python3.8/socket.py", line 787, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/jittor_utils/misc.py", line 51, in download_url_to_local
    urllib.request.urlretrieve(
  File "/usr/lib/python3.8/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 1393, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usr/lib/python3.8/urllib/request.py", line 1353, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno -3] Temporary failure in name resolution>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/docker-jittor-cuda/ts1.py", line 1, in <module>
    import jittor as jt
  File "/usr/local/lib/python3.8/dist-packages/jittor/__init__.py", line 25, in <module>
    from . import compile_extern
  File "/usr/local/lib/python3.8/dist-packages/jittor/compile_extern.py", line 557, in <module>
    setup_cutt()
  File "/usr/local/lib/python3.8/dist-packages/jittor/compile_extern.py", line 361, in setup_cutt
    install_cutt(cutt_path)
  File "/usr/local/lib/python3.8/dist-packages/jittor/compile_extern.py", line 314, in install_cutt
    download_url_to_local(url, filename, root_folder, true_md5)
  File "/usr/local/lib/python3.8/dist-packages/jittor_utils/lock.py", line 52, in inner
    ret = func(*args, **kw)
  File "/usr/local/lib/python3.8/dist-packages/jittor_utils/misc.py", line 60, in download_url_to_local
    raise RuntimeError(msg)
RuntimeError: <urlopen error [Errno -3] Temporary failure in name resolution>
Download File failed, url: https://codeload.github.com/Jittor/cutt/zip/v1.2, path: /root/.cache/jittor/cutt/cutt-1.2.zip
0.00B [00:20, ?B/s]
terminate called without an active exception
Aborted (core dumped)
```

## Minimal Reproduce
```
import jittor as jt

print(jt.__version__)

jt.flags.use_cuda = 0
```

## Expected behavior
下载 https://codeload.github.com/Jittor/cutt/zip/v1.2 手动加载到/root/.cache/jittor/cutt/中
再执行脚本，好像就能编译成功了，好像就正常了🤣   
显示版本号为1.3.1.27

**Comment by Jittor** [comment]
您可以python3.7 -m pip install jittor -U直接更新即可，我们尽快更新一下，因为jittor版本更新频繁，所以docker的版本有些滞后😁



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年12月17日(周五) 晚上11:21
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [Jittor/jittor] 给的docker里面的jittor 版本还是1.2.2.59，能不能提供下最新的版本的啊 (Issue #285)




 
Describe the bug
 
给的docker里面的jittor 版本还是1.2.2.59，能不能提供下最新的版本的啊
 
Full Log
 
***@***.***:/media# /usr/bin/python3 /media/docker-jittor-cuda/ts1.py
 [i 1217 15:17:09.308695 36 compiler.py:851] Jittor(1.2.2.59) src: /usr/local/lib/python3.8/dist-packages/jittor
 [i 1217 15:17:09.308783 36 compiler.py:852] g++ at /usr/bin/g++
 [i 1217 15:17:09.308817 36 compiler.py:853] cache_path: /root/.cache/jittor/default/g++
 [i 1217 15:17:09.330789 36 init.py:257] Found /usr/local/cuda/bin/nvcc(11.1.105) at /usr/local/cuda/bin/nvcc.
 [i 1217 15:17:09.352898 36 init.py:257] Found addr2line(2.34) at /usr/bin/addr2line.
 [i 1217 15:17:09.375301 36 compiler.py:893] pybind_include: -I/usr/include/python3.8 -I/usr/local/lib/python3.8/dist-packages/pybind11/include
 [i 1217 15:17:09.386878 36 compiler.py:895] extension_suffix: .cpython-38-x86_64-linux-gnu.so
 [i 1217 15:17:09.507388 36 init.py:169] Total mem: 31.31GB, using 10 procs for compiling.
 [i 1217 15:17:09.611967 36 jit_compiler.cc:21] Load cc_path: /usr/bin/g++
 [i 1217 15:17:09.612003 36 init.cc:54] Found cuda archs: []
 [i 1217 15:17:09.687928 36 init.py:257] Found mpicc(4.0.3) at /usr/bin/mpicc.
 [i 1217 15:17:09.707734 36 compiler.py:658] handle pyjt_include/usr/local/lib/python3.8/dist-packages/jittor/extern/mpi/inc/mpi_warper.h
 [i 1217 15:17:09.723767 36 compile_extern.py:289] Downloading nccl...
 [i 1217 15:17:09.762774 36 compile_extern.py:16] found /usr/local/cuda/include/cublas.h
 [i 1217 15:17:09.762906 36 compile_extern.py:16] found /usr/local/cuda/lib64/libcublas.so
 [i 1217 15:17:09.775295 36 compile_extern.py:16] found /usr/include/cudnn.h
 [i 1217 15:17:09.775351 36 compile_extern.py:16] found /usr/lib/x86_64-linux-gnu/libcudnn.so
 [i 1217 15:17:09.780108 36 compile_extern.py:16] found /usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so
 [i 1217 15:17:09.782843 36 compile_extern.py:16] found /usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so
 [i 1217 15:17:09.783217 36 compile_extern.py:16] found /usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so
 [i 1217 15:17:09.978729 36 compile_extern.py:16] found /usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so
 [i 1217 15:17:09.986669 36 compiler.py:658] handle pyjt_include/usr/local/lib/python3.8/dist-packages/jittor/extern/cuda/cudnn/inc/cudnn_warper.h
 [i 1217 15:17:09.997169 36 compile_extern.py:16] found /usr/local/cuda/include/curand.h
 [i 1217 15:17:09.997244 36 compile_extern.py:16] found /usr/local/cuda/lib64/libcurand.so
 1.2.2.59
 
Minimal Reproduce
 
Reproduce this error with a file or several lines of code.
 If it is not possible, leave it blank.
 
Expected behavior
 
A clear and concise description of what you expected to happen.
 
If you are submitting an issue for the first time, please refer to our guideline
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by liufeinuaa** [comment]
> 您可以python3.7 -m pip install jittor -U直接更新即可，我们尽快更新一下，因为jittor版本更新频繁，所以docker的版本有些滞后😁
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2021年12月17日(周五) 晚上11:21 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [Jittor/jittor] 给的docker里面的jittor 版本还是1.2.2.59，能不能提供下最新的版本的啊 (Issue #285) Describe the bug 给的docker里面的jittor 版本还是1.2.2.59，能不能提供下最新的版本的啊 Full Log ***@***.***:/media# /usr/bin/python3 /media/docker-jittor-cuda/ts1.py [i 1217 15:17:09.308695 36 compiler.py:851] Jittor(1.2.2.59) src: /usr/local/lib/python3.8/dist-packages/jittor [i 1217 15:17:09.308783 36 compiler.py:852] g++ at /usr/bin/g++ [i 1217 15:17:09.308817 36 compiler.py:853] cache_path: /root/.cache/jittor/default/g++ [i 1217 15:17:09.330789 36 init.py:257] Found /usr/local/cuda/bin/nvcc(11.1.105) at /usr/local/cuda/bin/nvcc. [i 1217 15:17:09.352898 36 init.py:257] Found addr2line(2.34) at /usr/bin/addr2line. [i 1217 15:17:09.375301 36 compiler.py:893] pybind_include: -I/usr/include/python3.8 -I/usr/local/lib/python3.8/dist-packages/pybind11/include [i 1217 15:17:09.386878 36 compiler.py:895] extension_suffix: .cpython-38-x86_64-linux-gnu.so [i 1217 15:17:09.507388 36 init.py:169] Total mem: 31.31GB, using 10 procs for compiling. [i 1217 15:17:09.611967 36 jit_compiler.cc:21] Load cc_path: /usr/bin/g++ [i 1217 15:17:09.612003 36 init.cc:54] Found cuda archs: [] [i 1217 15:17:09.687928 36 init.py:257] Found mpicc(4.0.3) at /usr/bin/mpicc. [i 1217 15:17:09.707734 36 compiler.py:658] handle pyjt_include/usr/local/lib/python3.8/dist-packages/jittor/extern/mpi/inc/mpi_warper.h [i 1217 15:17:09.723767 36 compile_extern.py:289] Downloading nccl... [i 1217 15:17:09.762774 36 compile_extern.py:16] found /usr/local/cuda/include/cublas.h [i 1217 15:17:09.762906 36 compile_extern.py:16] found /usr/local/cuda/lib64/libcublas.so [i 1217 15:17:09.775295 36 compile_extern.py:16] found /usr/include/cudnn.h [i 1217 15:17:09.775351 36 compile_extern.py:16] found /usr/lib/x86_64-linux-gnu/libcudnn.so [i 1217 15:17:09.780108 36 compile_extern.py:16] found /usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so [i 1217 15:17:09.782843 36 compile_extern.py:16] found /usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so [i 1217 15:17:09.783217 36 compile_extern.py:16] found /usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so [i 1217 15:17:09.978729 36 compile_extern.py:16] found /usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so [i 1217 15:17:09.986669 36 compiler.py:658] handle pyjt_include/usr/local/lib/python3.8/dist-packages/jittor/extern/cuda/cudnn/inc/cudnn_warper.h [i 1217 15:17:09.997169 36 compile_extern.py:16] found /usr/local/cuda/include/curand.h [i 1217 15:17:09.997244 36 compile_extern.py:16] found /usr/local/cuda/lib64/libcurand.so 1.2.2.59 Minimal Reproduce Reproduce this error with a file or several lines of code. If it is not possible, leave it blank. Expected behavior A clear and concise description of what you expected to happen. If you are submitting an issue for the first time, please refer to our guideline — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

**Comment by liufeinuaa** [comment]
👍
